env:
  - CXX=g++-4.8

services:
  - mysql

addons:
  postgresql: "9.3"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm install -g grunt-cli
  - mysql --help
  - mysql -e 'create database sandbox;'
  - mysql -e 'create database sandbox2;'
  - psql -c 'create database sandbox;' -U postgres
  - psql -c 'create database sandbox2;' -U postgres

sudo: false

after_script:
  - grunt test-coverage

language: node_js
node_js:
  - "4"
  - "5.6"
  - "5.12"
  - "stable"
