before_script:
  - mysql -e 'create database sandbox;'
  - mysql -e 'create database sandbox2;'
  - psql -c 'create database sandbox;' -U postgres
  - psql -c 'create database sandbox2;' -U postgres

language: node_js
node_js:
  - 0.6
  - 0.8