addons:
  postgresql: "9.3"

before_script:
  - npm install -g grunt-cli
  - mysql -e 'create database sandbox;'
  - mysql -e 'create database sandbox2;'
  - psql -c 'create database sandbox;' -U postgres
  - psql -c 'create database sandbox2;' -U postgres

after_script:
  - grunt test-coverage

language: node_js
node_js:
  - 0.10