name: 'Test'
on:
  pull_request:
    branches:
      - '*'
  # Run this workflow on pushes to develop, release and master
  # In order to check the full suite of apps/packages
  push:
    branches:
      - master
      - 'node-12'
jobs:
  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker-compose build
      - run: docker-compose up -d mysql postgres
      - run: sleep 10
      - run: docker-compose run patio

