name: 'Test'
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 0
      matrix:
        # 14 is not working yet
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker-compose build
      - run: docker-compose up -d mysql postgres
      - run: sleep 10
      # sandbox DB is created by the compose files
      - run: docker-compose run patio psql -h localhost -c 'create database sandbox2;' -U postgres
      - run: docker-compose run patio mysql -h 0.0.0.0 -e 'create database sandbox2;'
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run test
